def ShowHelp(arg1,arg2):
   print('****************************')
   print(' Valid Command and arguments')
   print('****************************')
   print('Width = nnn            -- Set Window Width')
   print('Height = nnn           -- Set Window Height')
   print('Position = nnn,nnn     -- Set Window Position')
   print('Title = \'xxx...\'       -- Set Window Title')    # shift to cover for \'
   print('Display                -- Display Image')
   print('Display = [Routine]    -- Display Image using [routine]')
   print('Kill MDisplay          -- Remove Display')
   print('RGB = bbb,ggg,rrr      -- Set RGB = r,g,b for routine 1')
   print('Routine = n            -- Select Routine n')
   print('Status                 -- Show Settings')
   print('Find Cameras           -- Find all cameras')
   print('Exit')